# fly.toml app configuration file generated for proto-go on 2023-11-28T10:36:33+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "proto-go"
primary_region = "syd"

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
PORT = "10000"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[[services]]
internal_port = 10000
protocol = "tcp"

[[services.ports]]
port = 10000
